name:                Titanic
version:             0.1.0.0
github:              "wojpok/Titanic"
license:             wojpok
author:              "Wojciech Pokój"
maintainer:          "wojtek.pokoj@gmail.com"
copyright:           "2025 Wojciech Pokój"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wojpok/Titanic#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -XTypeApplications
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
# TODO - fixes for later :)
- -Wno-name-shadowing
- -Wno-x-partial
- -Wno-incomplete-patterns
- -Wno-missing-signatures
- -Wno-unused-matches
- -Wno-missing-export-lists
- -Wno-unused-imports

library:
  source-dirs: src

executables:
  Titanic-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Titanic

tests:
  Titanic-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Titanic
